version: '3'
services:
  proxy:
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - ./proxy/proxy-nginx.conf:/etc/nginx/nginx.conf
      - ./data/example.test.crt:/etc/nginx/example.test.crt
      - ./data/example.test.key:/etc/nginx/example.test.key
      - ./data/logs/access.log:/var/log/nginx/access.log
      - ./data/logs/error.log:/var/log/nginx/access.log;
    ports:
      - "443:443"
      - "80:80"
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    volumes:
      - ./web/web-nginx.conf:/etc/nginx/nginx.conf
      - ./site:/usr/share/nginx/html
      - ./data/example.test.crt:/etc/nginx/example.test.crt
      - ./data/example.test.key:/etc/nginx/example.test.key
      - ./web/.htpasswd:/etc/nginx/.htpasswd
      - ./data/logs/access.log:/var/log/nginx/access.log
      - ./data/logs/error.log:/var/log/nginx/error.log
    ports: 
      - "8443:443"